# Log all requests at the Metadata level.
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: Metadata
  users: ["system:serviceaccount:sdz-operator-system:controller-manager"]
- level: Metadata
  users: ["system:serviceaccount:python-operator:python-operator-account"]
