# permissions for end users to edit securedropzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sdz-operator
    app.kubernetes.io/managed-by: kustomize
  name: securedropzone-editor-role
rules:
- apiGroups:
  - securedropzone.securedropzone.nl
  resources:
  - securedropzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - securedropzone.securedropzone.nl
  resources:
  - securedropzones/status
  verbs:
  - get
